### ISSUE TITLE
There a problem

### ISSUE THREAD

**Issue by michelandrus** [kaalleen/inkscape-bingo-extension#1]
I have a problem trying to change a value. Can you correct it? or may the problem is from my side? Thanks. 

usage: bingo.py [-h] [--output OUTPUT] [--tabs TABS]
                [--content-tab CONTENT_TAB] [--layout-tab LAYOUT_TAB]
                [--template-tab TEMPLATE_TAB] [--card_header CARD_HEADER]
                [--font_size FONT_SIZE] [--header_color HEADER_COLOR]
                [--num_color NUM_COLOR] [--rows ROWS] [--columns COLUMNS]
                [--grid_size GRID_SIZE] [--render_grid RENDER_GRID]
                [--stroke_width STROKE_WIDTH] [--num_range NUM_RANGE]
                [--free_center FREE_CENTER] [--free_rows FREE_ROWS]
                [--create_area CREATE_AREA] [--id IDS]
                [--selected-nodes SELECTED_NODES]
                [INPUT_FILE]
bingo.py: error: argument --grid_size: invalid int value: '20.00'

Whatever the number I put in, the extension sends me back that message.

**Comment by kaalleen** [comment]
Thank you. Should be fixed here: https://github.com/kaalleen/inkscape-bingo-extension/releases/tag/v0.0.10
